FROM python:3.13-slim

WORKDIR /api
RUN pip install --no-cache-dir "fastapi[standard]" elasticsearch
COPY . .
ENV ELASTICSEARCH_HOST=http://elasticsearch:9200
CMD ["sh",  "-c", "fastapi run backend/server.py --port 9567"]

